import { Platform, StyleSheet } from 'react-native';
export const colors = {
  background: '#F5F5EF',
  paper: '#FFFFFF',
  ink: '#173A32',
  muted: '#63746C',
  green: '#245B48',
  pale: '#E7EFE7',
  line: '#DCE3DB',
  gold: '#D0AF6C',
  amber: '#775423',
  amberBg: '#F7EFD9',
  error: '#9C3836',
  errorBg: '#FBECE8',
};
export const mono = Platform.select({ ios: 'Menlo', default: 'monospace' });
export const s = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  grow: { flex: 1 },
  stack: { gap: 16 },
  card: {
    backgroundColor: colors.paper,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 20,
    gap: 16,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 2,
    color: colors.muted,
  },
  title: {
    fontSize: 30,
    lineHeight: 37,
    fontWeight: '600',
    letterSpacing: -1,
    color: colors.ink,
  },
  heading: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.ink,
    letterSpacing: -0.4,
  },
  body: { fontSize: 14, lineHeight: 22, color: colors.muted },
  small: { fontSize: 12, lineHeight: 19, color: colors.muted },
  mono: { fontFamily: mono, fontSize: 12, lineHeight: 21, color: colors.ink },
  label: { fontSize: 12, color: colors.ink, fontWeight: '600' },
  field: {
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#FAFBF8',
    borderWidth: 1,
    borderColor: colors.line,
    color: colors.ink,
    fontSize: 14,
  },
  divider: { height: 1, backgroundColor: colors.line },
  center: { alignItems: 'center', paddingVertical: 24, gap: 14 },
});
